### ISSUE TITLE
Unterlagen zur Schulung

### ISSUE THREAD

**Issue by j4il3r** [ppedvAG/Softwaretest_25_06_2020#1]
Hallo @AndreRRR ,

könntest du mir bitte noch die Unterlagen/Folien der Schulung zukommen lassen.

Danke. 

Viele Grüße
Philipp

**Comment by AndreRRR** [comment]
Die Unterlage habe ich in das Premiumportal der ppedv Hochgeladen, dort wirst du sie nun finden.
Viele Grüße
André

**Comment by j4il3r** [comment]
Danke

**Comment by j4il3r** [comment]
Hallo @AndreRRR 

ich hätte doch noch eine kleine Bitte.
Könntest du mir auch die Folien des ersten Schulungstages bzgl. u.A. .NET Framework im Portal anhängen bzw. zukommen lassen?

Danke. 

Viele Grüße
Philipp

**Comment by AndreRRR** [comment]
Kein Problem, ich habe die Übersicht nun mit dazu gepackt. Im Portal wirst du nun beide Präsentationen finden.

**Comment by j4il3r** [comment]
Hallo @AndreRRR,
Ich habe gerade nachgeschaut. Bei mir erscheint leider immer noch nur die eine Präsentation :( 
Die Übersicht kann ich leider nirgends finden :(
Dies ist schon das korrekte Portal? - https://ppedv.de/service/MeinKonto.aspx

**Comment by j4il3r** [comment]
Hallo @AndreRRR ,

evtl. ist mein vorheriger Post untergegangen.
Könntest du hier bitte nochmals nachschauen. Andernfalls kannst du mir diese auch gerne per Mail zukommen lassen.

Danke.

Viele Grüße
Philipp

**Comment by AndreRRR** [comment]
Vor ein paar Tagen habe die Unterlagen erneut hochgeladen, ich habe aber vergessen hier bescheid zu sagen. Sorry dass es so lange gedauert hat. 

Gruß
André

**Comment by j4il3r** [comment]
Kein Problem :)
